- name: Configure cron tasks
  cron:
    name: "Backup {{ item.name_backup }}"
    minute: "{{ item.cron.minute }}"
    hour: "{{ item.cron.hour  }}"
    day: "{{ item.cron.day }}"
    weekday: "{{ item.cron.weekday }}"
    month: "{{ item.cron.month }}"
    job: |

          /usr/local/bin/docker_mongo_backup.sh -n {{ item.name_backup }} -s {{ item.src_backup }} -d {{ item.aws_dest }} -t {{ item.tmp_dir }} -r {{ item.retain_count }} -e {{ item.filter_date }} >> /var/log/files_backup.log 2>&1 

  with_items: "{{ backup.paths }}"