- name: Install dependencies
  include_tasks: install_dependencies.yml
  tags: install

- name: Create configs
  include_tasks: create_configs.yml
  tags: config

- name: Configure cron
  include_tasks: configure_cron.yml
  tags: cron

- name: pyhton3, apprise install
  include_tasks: install_python_apprise.yml
  tags: cron